import Head from "next/head";
import Link from "next/link";
import Layout from "../components/Layout";
import styles from "../styles/components/index/index.module.scss";

export default function Home() {
	return (
		<Layout>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.container}>
				<h1>
					Welcome to <a href="https://nextjs.org">My project</a>
				</h1>
				<Link href="/posts/showpost">
					<a>See my posts</a>
				</Link>
			</main>
		</Layout>
	);
}
